##This workflow is used to test the CRUD operations of the Spring Boot application using Maven, it uses a wallet to connect to the Oracle database, which is encrypted and stored in a secret. The workflow is triggered on push and pull request events to the main branch.
name: CRUD Springboot Testing

on:
  workflow_dispatch:
  push:
    branches: 
      - localDeploy
      - deployPantai
  pull_request:
    branches: 
      - deployPantai
      - localDeploy


jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120
        install-dependencies: true
  #Decodes wallet.enc from base 64 enc and then decrypts it using openssl
    - name : Decode wallet.enc from base64 secret
      run: |
        cd oci-react-samples/MtdrSpring
        echo "$WALLET_ENC_B64" | base64 -d > wallet.enc
      env:
        WALLET_ENC_B64: ${{secrets.WALLET_ENC_B64}}
        
    #Step to decrypt wallet
    - name: Decrypt wallet
      run: |
        cd oci-react-samples/MtdrSpring
        openssl enc -d -aes-256-cbc -in wallet.enc -out Wallet_TEAM11.zip -pass pass:$WALLET_PASSWORD
      env:
        WALLET_PASSWORD: ${{secrets.WALLET_PASSWORD}}

    #Step to unzip the wallet
    - name : Unzip wallet
      run: |
        cd oci-react-samples/MtdrSpring
        unzip Wallet_TEAM11.zip -d Wallet_TEAM11

    - name : Test if wallet was correctly 
      run: |
        cd oci-react-samples/MtdrSpring/Wallet_TEAM11
        ls

  #Changing wallet path in applicatio.properties
    - name : Set wallet path, username and password in application.properties for VM running action.
      run: |
        WALLET_PATH="$(pwd)/oci-react-samples/MtdrSpring/Wallet_TEAM11"
        sed -i "s|spring.datasource.url=jdbc:oracle:thin:@.*|spring.datasource.url=jdbc:oracle:thin:@team11_high?TNS_ADMIN=${WALLET_PATH}|" oci-react-samples/MtdrSpring/backend/src/main/resources/application.properties
        sed -i "s|spring.datasource.username=.*|spring.datasource.username=TODOUSER|" oci-react-samples/MtdrSpring/backend/src/main/resources/application.properties
        sed -i "s|spring.datasource.password=.*|spring.datasource.password=Copiloto12345|" oci-react-samples/MtdrSpring/backend/src/main/resources/application.properties
        cat oci-react-samples/MtdrSpring/backend/src/main/resources/application.properties

  #Changing OracleConfiguration.java to use DB configuration for local, instead of using the OCI one, it prevents testing from succeeding
    - name: Set OracleConfiguration.java isLocal boolean to true
      run: |    
        sed -i "s|final boolean isLocal = false;.*|final boolean isLocal = true;|" oci-react-samples/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/config/OracleConfiguration.java
        cat oci-react-samples/MtdrSpring/backend/src/main/java/com/springboot/MyTodoList/config/OracleConfiguration.java
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up node 20 
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build with Maven
      run: |
          cd oci-react-samples
          cd MtdrSpring
          cd backend
           mvn clean test
           echo "Endpoints tested"
    
