
name: CRUD Springboot Testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120
        install-dependencies: true
  #Decodes wallet.enc from base 64 enc and then decrypts it using openssl
    - name : Decode wallet.enc from base64 secret
      run: |
        cd oci-react-samples/MtdrSpring
        base64 -d -i $WALLET_ENC_B64 > wallet.enc
      env:
        WALLET_ENC_64: ${{secrets.WALLET_ENC_B64}}
        
    #Step to decrypt wallet
    - name: Decrypt wallet
      run: |
        cd oci-react-samples/MtdrSpring
        openssl enc -aes-256-cbc -in wallet.enc -out Wallet_TEAM11.zip -k $WALLET_PASSWORD
      env:
        WALLET_PASSWORD: ${{secrets.WALLET_PASSWORD}}

    #Step to unzip the wallet
    - name : Unzip wallet
      run: |
        cd oci-react-samples/MtdrSpring
        unzip Wallet_TEAM11.zip 
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up node 20 
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build with Maven
      run: |
          cd oci-react-samples
          cd MtdrSpring
          cd backend
           mvn clean test
           echo "Endpoints tested"
    
